workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Generate Android platform files
        script: |
          flutter create . --platforms=android --org com.mylittlediary
      - name: Force compileSdk and targetSdk to 36
        script: |
          echo "flutter.compileSdkVersion=36" >> android/local.properties
          echo "flutter.targetSdkVersion=36" >> android/local.properties
          echo "----- local.properties -----"
          cat android/local.properties
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
